const stakingABI = [
  {
    "inputs":[{"internalType":"uint256","name":"amount","type":"uint256"}],
    "name":"stakeOld",
    "outputs":[],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[{"internalType":"uint256","name":"amount","type":"uint256"}],
    "name":"stakeNew",
    "outputs":[],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[{"internalType":"address","name":"user","type":"address"}],
    "name":"getStakeCountOld",
    "outputs":[{"internalType":"uint256","name":"","type":"uint256"}],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[{"internalType":"address","name":"user","type":"address"}],
    "name":"getStakeCountNew",
    "outputs":[{"internalType":"uint256","name":"","type":"uint256"}],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[{"internalType":"address","name":"","type":"address"},{"internalType":"uint256","name":"","type":"uint256"}],
    "name":"stakesOld",
    "outputs":[
      {"internalType":"uint256","name":"amount","type":"uint256"},
      {"internalType":"uint256","name":"startTime","type":"uint256"},
      {"internalType":"uint256","name":"lockPeriod","type":"uint256"},
      {"internalType":"uint256","name":"aprBps","type":"uint256"},
      {"internalType":"bool","name":"unstaked","type":"bool"}
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[{"internalType":"address","name":"","type":"address"},{"internalType":"uint256","name":"","type":"uint256"}],
    "name":"stakesNew",
    "outputs":[
      {"internalType":"uint256","name":"amount","type":"uint256"},
      {"internalType":"uint256","name":"startTime","type":"uint256"},
      {"internalType":"uint256","name":"lockPeriod","type":"uint256"},
      {"internalType":"uint256","name":"aprBps","type":"uint256"},
      {"internalType":"bool","name":"unstaked","type":"bool"}
    ],
    "stateMutability":"view",
    "type":"function"
  }
];

const erc20ABI = [
  {
    "constant":true,
    "inputs":[{"name":"owner","type":"address"}],
    "name":"balanceOf",
    "outputs":[{"name":"","type":"uint256"}],
    "type":"function"
  },
  {
    "constant":false,
    "inputs":[
      {"name":"spender","type":"address"},
      {"name":"amount","type":"uint256"}
    ],
    "name":"approve",
    "outputs":[{"name":"","type":"bool"}],
    "type":"function"
  },
  {
    "constant":true,
    "inputs":[
      {"name":"owner","type":"address"},
      {"name":"spender","type":"address"}
    ],
    "name":"allowance",
    "outputs":[{"name":"","type":"uint256"}],
    "type":"function"
  }
];
